name = "OpenSOAP"
uuid = "2c6d34cf-35ee-49d7-b3b5-1bd6781e04ee"
authors = ["Thanasi Pantazides <thanasipantazides@gmail.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"
InfiniteOpt = "20393b10-9daf-11e9-18c9-8db751c92c57"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
SatelliteToolboxCelestialBodies = "b0edd99f-a7ca-4aa6-9a1e-a53e8f506046"
SatelliteToolboxGeomagneticField = "9fc549ba-b5d7-49a2-b268-8171e5fb6e89"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
FiniteDiff = "2.27.0"
ForwardDiff = "0.10.38"
InfiniteOpt = "0.5.9"
Makie = "0.22.4"
OptimalControl = "1.0.2"
